STS.P1.Planetarium/STS.P1.Planetarium/Controllers/BookingController.cs
using STS.P1.Planetarium.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace STS.P1.Planetarium.Controllers
{
    public class BookingController : Controller
    {
        private BookingRepository db = new BookingRepository();
        PlanetariumDB planetariumDatabase = new PlanetariumDB();
        private ReservationModel reservationModel = new ReservationModel();
        private MovieModel movieModel = new MovieModel();
        private float? reservationAmount;
        private String currentMovieId;

        
        // GET: Booking
        public ActionResult Reservation()
        {
            var planetariums = db.GetAllPlanetariums().ToList<PlanetariumModel>();

            reservationModel.AvailablePlanetariums.Add(new SelectListItem { Text = "Choose a Planetarium...", Value = "0" });
            foreach (PlanetariumModel planetarium in planetariums)
            {
                reservationModel.AvailablePlanetariums.Add(new SelectListItem { Text = planetarium.PlanetariumName, Value = planetarium.PlanetariumId.ToString() });                
            }

            ViewData["PlanetariumDropdown"] = reservationModel.AvailablePlanetariums;
                        
            return View();          
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult GetMoviesById(string planetariumId)
        {
            if (String.IsNullOrEmpty(planetariumId))
            {
                throw new ArgumentNullException("planetariumId");
            }
            int id = 0;
            bool isValid = Int32.TryParse(planetariumId, out id);            
            var movies = db.GetAllMoviesByPlanetarium(id);
            var result = (from s in movies
                          select new
                          {
                              id = s.MovieId,
                              name = s.MovieName
                          }).ToList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult GetMovieDetialsById(string movieId)
        {
            if (String.IsNullOrEmpty(movieId))
            {
                throw new ArgumentNullException("movieId");
            }
            int id = 0;
            bool isValid = Int32.TryParse(movieId, out id);            
            var MovieResult = db.GetAllMovieDetailsByMovieId(id);
            var result = (from r in MovieResult
                         select new
                         {
                             MovieId = r.MovieId,
                             MovieName = r.MovieName,
                             Show1 = r.Show1,
                             Show2 = r.Show2,
                             Show3 = r.Show3,
                             Show4 = r.Show4,
                             TicketPrice = r.TicketPrice,
                             TrailerURL = r.TrailerURL,
                             MovieLength = r.MovieLength,
                             IsActive = r.IsActive,
                             ReleaseDate = r.ReleaseDate
                         }).FirstOrDefault();

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public RedirectToRouteResult GetMovieDetialsById(String ReservationTotalAmount, String MovieDropdown)
        {
            var amount = Convert.ToSingle(ReservationTotalAmount.Replace(" $",""));
            var MovieId = MovieDropdown;
            return RedirectToAction("Payment", new { ReservationTotalAmount = amount, MovieId = MovieDropdown });
        }


        public ActionResult Payment(float? ReservationTotalAmount, String MovieId)
        {
            reservationAmount = ReservationTotalAmount;
            currentMovieId = MovieId;
            return View();
        }

        [HttpPost]
        public ActionResult Payment(BookingModel book,String Name, String EmailId, String ContactNo, String StreeName, String CityName, String StateCode, String zipCode, String cardNumber, String cardExpiryDate, String cvvCode)
        {
            //reservationAmount = ReservationTotalAmount;
            String bookingId = "ABCDEF123";              
            BookingModel bookingModel = new BookingModel { Name = Name, EmailId = EmailId, ContactNo = ContactNo, BookingAmount = "25.00", StreeName = StreeName, CityName = CityName, StateCode = StateCode, zipCode = zipCode, cardNumber = cardNumber, cardExpiryDate = cardExpiryDate, cvvCode = cvvCode, MovieId = 2, IsActive = true, BookingToken = bookingId, NoOfPersons = "2" };
            if (bookingModel != null)
            {
                if (ModelState.IsValid)
                {
                    planetariumDatabase.Booking.Add(bookingModel);
                    planetariumDatabase.SaveChanges();
                }
                else
                {
                    return View(book);
                }
            }
            
            return RedirectToAction("PaymentConfirmation", new { BookingToken = bookingId });
        }

        public ActionResult PaymentConfirmation(String bookingToken)
        {

            ViewData["BookingToken"] = bookingToken;
            return View();
        }
    }
}

STS.P1.Planetarium/STS.P1.Planetarium/Views/Booking/Payment.cshtml
@model STS.P1.Planetarium.Models.BookingModel

@{
    ViewBag.Title = "Payment - STS Planetarium";
}

<div class="row">
    <div class="col-md-12">
        <section id="reservatioPaymentForm" style="padding-left:7em">
            <div class="container">
                @using (Html.BeginForm("Payment", "Booking", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <h2>2. Provide Payment Details..</h2>
                    <hr />
                    <fieldset>
                        <div>
                            <label>Name*:</label>
                        </div>
                        
                        <div>
                            <div>
                                @Html.TextBoxFor(m => m.Name)
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger"})
                                @*<input class='required email' type="text" name="owner_name" id='owner_name' maxlength="64" value="" />*@
                            </div>
                            <label>Contact Email*:</label>
                        </div>
                        <div>
                            <div>
                                @Html.TextBoxFor(m => m.EmailId)
                                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                                @*<input class='required phone' type="text" name="owner_email" id='owner_email' maxlength="50" value="" />*@
                            </div>
                            <label>Contact Phone*:</label>
                        </div>

                        <div>
                            <div>
                                @Html.TextBoxFor(m => m.ContactNo)
                                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                                @*<input type="text" name="owner_phone" id='owner_phone' maxlength="64" value="" />*@
                            </div>
                        </div>

                        <div>
                            <label>Billing Address:</label>
                            <div style="padding-top:1em">
                                @*<input type="text" name="business_address" id='business_address' maxlength="50" value="" placeholder='street' /><br />*@
                                @Html.TextBoxFor(m => m.StreeName, new { placeholder = "street name" })
                                @Html.ValidationMessageFor(model => model.StreeName, "", new { @class = "text-danger" })
                                @Html.TextBoxFor(m => m.CityName, new { placeholder = "city"})
                                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
                                @*<input type="text" name="business_city" id='business_city' maxlength="50" value="" placeholder='city' /><br />*@
                                <div>
                                    @Html.DropDownListFor(m => m.StateCode, STS.P1.Planetarium.Models.BookingModel.StateListItems(), "Select your state...")
                                    
                                    <div style="padding-top:0.8em">
                                        @Html.TextBoxFor(m => m.zipCode, new { placeholder = "zip code" })
                                        @Html.ValidationMessageFor(model => model.zipCode, "", new { @class = "text-danger" })
                                        @*<input class='fourth' type="text" name="business_zip" id='business_zip' maxlength="10" value="" placeholder='zip' style="width:150px" />*@
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <label>Card Details:</label>
                            <div style="padding-top:1em">
                                @Html.TextBoxFor(m => m.cardNumber, new { placeholder = "card number" })
                                @Html.ValidationMessageFor(model => model.cardNumber, "", new { @class = "text-danger" })
                                @*<input class='fourth' type="text" name="card_number" id='card_number' maxlength="10" value="" placeholder='Card Number(no spaces)'/><br/>*@
                                @Html.TextBoxFor(m => m.cardExpiryDate, new { placeholder = "card expiry date" })
                                @Html.ValidationMessageFor(model => model.cardExpiryDate, "", new { @class = "text-danger" })
                                @*<input class='fourth' type="text" name="card_date" id='card_Date' maxlength="10" value="" placeholder='Card Expiry(mm/dd/yyyy)' />*@
                                @Html.TextBoxFor(m => m.cvvCode, new { placeholder = "CVV Code" })
                                @Html.ValidationMessageFor(model => model.cvvCode, "", new { @class = "text-danger" })
                                @*<input class='fourth' type="text" name="cvv_code" id='cvv_code' maxlength="10" value="" placeholder='CVV Code' style="width:150px" />*@
                            </div>
                        </div>                        
                    </fieldset>

                    <div class="span3" style="padding-left:1em">
                        <input type="submit" value="Confirm Your purchase >>" class="btn btn-primary btn-block" />
                        @*<a class="btn btn-primary btn-block" href="@Url.Action("PaymentConfirmation", "Booking")">Confirm Your purchase</a>*@
                    </div>
                }
            </div>
     </section>
</div>
    @*<div class="col-md-4">
            <section id="socialLoginForm">
                @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
            </section>
        </div>*@
</div>

STS.P1.Planetarium/STS.P1.Planetarium/Views/Booking/PaymentConfirmation.cshtml
@{
    ViewBag.Title = "PaymentConfirmation";
}

<div class="row">
    <div class="col-md-12">
        <section id="reservatioPaymentConfirmation" style="padding-left:5em">
            <h2>3. Booking confirmation..</h2>
            <hr />
            <div class="container">
                <h3>Thank you! your booking is confirmed. You will receive an e-ticket to your email once the payment is approved.</h3>
            </div><br />
            <div style="padding-left:4em"><h4>Your Booking ID: </h4><label>@ViewData["BookingToken"]</label></div>
        </section>
    </div>
</div>

STS.P1.Planetarium/STS.P1.Planetarium/Views/Booking/Reservation.cshtml
@model STS.P1.Planetarium.Models.ReservationModel


@{
    ViewBag.Title = "Reservation - STS Planetarium";
}

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js">
</script>

<script type="text/javascript">
   
    $(function () {
        $("#PlanetariumDropdown").change(function () {
            var selectedItem = $(this).val();
            var ddlMovies = $("#MovieDropdown");
            //var statesProgress = $("#states-loading-progress");
            //statesProgress.show();
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.RouteUrl("GetMoviesById"))",
                data: { "planetariumId": selectedItem },
                success: function (data) {
                    ddlMovies.html('');
                    ddlMovies.append($('<option></option>').val(0).html('Choose a Movie...'));
                    $.each(data, function (id, option) {
                        ddlMovies.append($('<option></option>').val(option.id).html(option.name));
                    });
                    //statesProgress.hide();
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve states.');
                    alert(thrownError);
                    //statesProgress.hide();
                }
            });
        });
    });
    $(function () {
        $("#MovieDropdown").change(function () {
            var selectedItem = $(this).val();
            var ddlTimings = $("#TimingsDropdown");
            var banner = $("#bannerSection");
            var movieName = $("#bannerSection").find('#reservationMoiveName');
            var movieDate = $("#bannerSection").find('#reservationMoiveDate');
            var movieRunTime = $("#bannerSection").find('#reservationRuneTime');
            var trailerURL = $("#bannerSection").find('#movieTrailerURL');
            
            //var statesProgress = $("#states-loading-progress");
            //statesProgress.show();
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.RouteUrl("GetMovieDetialsById"))",
                data: { "movieId": selectedItem },
                success: function (data) {
                    var resultMovieName = $(data).attr("MovieName");
                                       
                    var movieLength = $(data).attr("MovieLength");
                    var movieTrailerURL = $(data).attr("TrailerURL");
                    var releaseDate = $(data).attr("ReleaseDate");
                    var show1 = $(data).attr("Show1") + ':00';
                    var show2 = $(data).attr("Show2") + ':00';
                    var show3 = $(data).attr("Show3") + ':00';
                    var show4 = $(data).attr("Show4") + ':00';
                    //alert("resultMovieName");
                    //alert("show1");
                    banner.show();
                    movieName.html(resultMovieName);
                    movieDate.html(releaseDate);
                    movieRunTime.html(movieLength);
                    trailerURL.attr('src', movieTrailerURL);
                    movieName.delay(100).fadeIn();
                    movieDate.delay(100).fadeIn();
                    movieRunTime.delay(100).fadeIn();
                    trailerURL.delay(100).fadeIn();

                    ddlTimings.html('');
                    ddlTimings.append($('<option></option>').val(0).html('Choose a Timing...'));
                    ddlTimings.append($('<option></option>').val(show1).html(show1));
                    ddlTimings.append($('<option></option>').val(show2).html(show2));
                    ddlTimings.append($('<option></option>').val(show3).html(show3));
                    ddlTimings.append($('<option></option>').val(show4).html(show4));

                //statesProgress.hide();
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Failed to retrieve Movie Details.');
                alert(thrownError);
                //statesProgress.hide();
            }
        });
    });
    });

    $(function () {
        $("#PersonsCountDropdown").change(function () {
            var Count = $('#PersonsCountDropdown option:selected').text();
            var selectedItem = $("#MovieDropdown").val();
            var totalAmount = $("#ReservationTotalAmount");
                                    
            $.ajax({
                cache: false,
                type: "GET",
                url: "@(Url.RouteUrl("GetMovieDetialsById"))",
                data: { "movieId": selectedItem },
            success: function (data) {
                var ticketAmount = $(data).attr("TicketPrice").toFixed(2) * parseFloat(Count);
                //alert(ticketAmount);
                totalAmount.val(ticketAmount.toFixed(2) + " $");
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Failed to retrieve Movie Details.');
                alert(thrownError);
                //statesProgress.hide();
            }
        });
    });
    }); 

</script>

<div class="row" id="bookingsScreen">
    <div class="col-md-6">
        <section id="bookingSection" style="padding-left:5em">
          
            <div class="container">
                <h2>1. Select a movie..</h2>
                <hr />
                @using (Html.BeginForm("GetMovieDetialsById", "Booking", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div id="bookingForm" style="padding-left:5em">
                        <div>
                            <h4>Planetarium:</h4>                            
                            <div class="dropdown" style="padding-left:2em">
                                
                                    @Html.DropDownList("PlanetariumDropdown", ViewData["PlanetariumDropdown"] as List<SelectListItem>)

                                @*<select>
                                    <option value="">Select a Planetarium...</option>
                                    <option value="1">The Arvin Gottlieb Planetarium</option>
                                    <option value="2">The Union Station Planetarium</option>
                                    <option value="3">NorthWest Planetarium</option>
                                </select>*@
                            </div>
                        </div>
                        <div>
                            <h4>Movie Name:</h4>
                            <div class="dropdown" style="padding-left:2em">
                                @Html.DropDownList("MovieDropdown", new SelectList(string.Empty, "Value", "Text"), "Movies...")                                                              
                            </div>
                        </div>
                        <div>
                            <h4>Timings:</h4>
                            <div class="dropdown" style="padding-left:2em">
                                @Html.DropDownList("TimingsDropdown", new SelectList(string.Empty, "Value", "Text"), "Show Times...")                               
                                
                            </div>
                        </div>
                        <div>
                            <h4>No. of Persons:</h4>
                            <div id="PersonsCountDropdown" style="padding-left:2em">
                                <select name="PersonsCountDropdown">
                                    <option value="0">Select Count...</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                </select>
                            </div>                            
                        </div><br />
                        <div>
                            <h4>Total Amount:</h4>
                            
                            @*<label id="ReservationTotalAmount" name="ReservationAmount" style="padding-left:2em"></label>*@                            
                            <input id="ReservationTotalAmount" name="ReservationTotalAmount" type="text" value=""/>
                            
                        </div><br />
                        <div class="span2">
                            <input type="submit" value="Book Now >>" class="btn btn-primary btn-block"/>
                            @*<a class="btn btn-primary btn-block" type="submit" href="@Url.Action("Payment", "Booking")">Book Now!</a>*@
                        </div>
                    </div>   
                }
            </div>
        </section>
    </div>
    <div class="divider" style="position: absolute; left: 50%; top: 25%; bottom: 10%; border-left: 1px solid white;"></div>
    <div class="col-md-3">
        <section id="bannerSection" style="display:none">
            <h3>Movie Details</h3>
            @*<div class="container">
                <div id="row">
                    <img src="~/Content/Images/Movies/Journey-to-Space-3D-the-orange-cat.jpg" alt=""/>  
                </div>
            </div>*@
            <div class="container">
                <div id="row">
                    <div>
                        <h4>Movie Name: </h4><label id="reservationMoiveName" style="padding-left:2em;font-weight:bold"></label>
                    </div><br />
                    <div>
                        <h4>Release Date: </h4><label id="reservationMoiveDate" style="padding-left:2em;font-weight:bold"></label>
                    </div><br />
                    <div>
                        <h4>Run Time: </h4><label id="reservationRuneTime" style="padding-left:2em;font-weight:bold"></label>
                    </div><br />
                    <h4>Trailer: </h4>
                    <div style="padding-left:2em">
                        <iframe id="movieTrailerURL" width=" 500" height="338" src="" frameborder="1" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
       </section>
    </div>
    <div class="col-md-2">
        <div>

        </div>
    </div>
       
</div>