STS.P1.Planetarium/STS.P1.Planetarium/Controllers/TechnicalController.cs
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using STS.P1.Planetarium.Models;
using System.IO;

namespace STS.P1.Planetarium.Controllers
{
    public class TechnicalController : Controller
    {
        PlanetariumDB planetariumDatabase = new PlanetariumDB();
        BookingRepository planetariumDB = new BookingRepository();
        private ReservationModel reservationModel = new ReservationModel();
        private static readonly string _awsAccessKey = ConfigurationManager.AppSettings["_awsAccessKey"];

        private static readonly string _awsSecretKey = ConfigurationManager.AppSettings["_awsSecretKey"];

        private static readonly string _bucketName = ConfigurationManager.AppSettings["_awsBucketName"];
        private BookingRepository db = new BookingRepository();

        String returnResponse = "";
                
        // GET: Technical
        public ActionResult UploadDocument()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        // GET: Technical
        public ActionResult UploadDocument(string technicalDocument, string DocumentName, string business_url)
        {
            string fileName = "";

            foreach(String fileDocument in Request.Files)
            {
                HttpPostedFileBase hpf = Request.Files[fileDocument] as HttpPostedFileBase;
                fileName = hpf.FileName;
                fileName = fileName.Substring(fileName.LastIndexOf("\\")+1);
                PutObjectResponse response;

                if (User.Identity.IsAuthenticated)
                {                   

                    try
                    {
                        IAmazonS3 client;
                        using (client = Amazon.AWSClientFactory.CreateAmazonS3Client(_awsAccessKey, _awsSecretKey, Amazon.RegionEndpoint.USWest2))
                        {
                            var request = new PutObjectRequest()
                            {
                                BucketName = _bucketName,
                                CannedACL = S3CannedACL.PublicRead,//PERMISSION TO FILE PUBLIC ACCESIBLE
                                Key = string.Format("UPLOADS/{0}", fileName),
                                InputStream = hpf.InputStream//SEND THE FILE STREAM                                
                            };
                            
                            response = client.PutObject(request);
                                                                                    
                        }
                    }
                    catch (Exception ex)
                    {
                        ViewBag.resultDocumentMessage = "Document not submitted - " + ex.Message;
                        return View();
                    }

                    String documentURL = ConfigurationManager.AppSettings["_awsDocumentPath"] + string.Format("UPLOADS/{0}", fileName);
                    
                    ViewBag.resultDocumentMessage = "Document Uploaded Succesfully...";
                    DocumentModel docModel = new DocumentModel { DocumentName = DocumentName, LocationURL = documentURL, updloadDate = DateTime.Now, DocumentDescription = "This document is not a technical paper" };
                    if (docModel != null)
                    {
                        planetariumDatabase.Document.Add(docModel);
                        planetariumDatabase.SaveChanges();
                    }
                    return View();
                }
            }
            return RedirectToAction("Login", "Account");
        }

        public ActionResult EditUploadedDocument()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            return RedirectToAction("Login", "Account");
        }

        public ActionResult publish()
        {
            if (User.Identity.IsAuthenticated)
            {
                var planetariums = planetariumDB.GetAllPlanetariums().ToList<PlanetariumModel>();
                reservationModel.AvailablePlanetariums.Add(new SelectListItem { Text = "Choose a Planetarium...", Value = "0" });
                foreach (PlanetariumModel planetarium in planetariums)
                {
                    reservationModel.AvailablePlanetariums.Add(new SelectListItem { Text = planetarium.PlanetariumName, Value = planetarium.PlanetariumId.ToString() });
                }

                ViewData["PlanetariumDropdown"] = reservationModel.AvailablePlanetariums;                

                return View();
            }
            return RedirectToAction("Login", "Account");
            
        }

        [HttpPost]
        public ActionResult publish(MovieModel reservationObj)
        {

            //var planetariums = db.GetAllPlanetariums().ToList<PlanetariumModel>();
            PlanetariumDB planetDB = new PlanetariumDB();

            
            if (User.Identity.IsAuthenticated)
            {                
                MovieModel model = new MovieModel();
                model.MovieName = reservationObj.MovieName;
                model.Show1 = reservationObj.Show1;
                model.Show2 = reservationObj.Show2;
                model.Show3 = reservationObj.Show3;
                model.Show4 = reservationObj.Show4;
                model.TicketPrice = reservationObj.TicketPrice;
                model.TrailerURL = reservationObj.TrailerURL;
                model.ReleaseDate = reservationObj.ReleaseDate;
                model.MovieLength = reservationObj.MovieLength;
                model.IsActive = reservationObj.IsActive;
                model.PlanetariumId = 1;

                planetDB.Movie.Add(model);
                planetDB.SaveChanges();
                ViewBag.resultPublishMessage = "Movie published Sucessfully...!";
                return RedirectToAction("publish");
            }
            return RedirectToAction("Login", "Account");

        }


        public ActionResult publishEdit()
        {
            if (User.Identity.IsAuthenticated && Session["AccountKind"].Equals("A"))
            {
                return View();
            }
            return RedirectToAction("Login", "Account");
        }



    }
}

STS.P1.Planetarium/STS.P1.Planetarium/Views/Technical/EditUploadedDocument.cshtml
@{
    ViewBag.Title = "EditUploadedDOcument";    
}


<div class="row">
    <div class="col-md-12">
        <section id="reservatioPaymentForm" style="padding-left:7em">
            <div class="container">
                @using (Html.BeginForm("Payment", "Booking", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <h2>Edit Technical Papers..</h2>
                    <hr />
                    <fieldset>

                        <label>Existing Paper: </label>
                        <select name="business_state" class="dropdown" style="height:35px;width:150px">
                            <option value="">Select paper...</option>
                            <option value='AL'>Black Holes</option>
                            <option value='AL'>Interstellar</option>
                            <option value='AL'>ET</option>                            
                        </select>

                        <div>
                            <br />
                            <label>Paper Title*:</label>
                        </div>

                        <div>
                            <div>
                                <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                            </div><br />
                            <label>Author Name*:</label>
                        </div>

                        <div>
                            <div>
                                <input class='required phone' type="text" name="owner_phone" id='owner_phone' maxlength="50" value="" />
                            </div><br />
                            <label>Author Contact Email*:</label>
                        </div>

                        <div>
                            <div>
                                <input type="text" name="business_url" id='business_url' maxlength="64" value="" />
                            </div><br />                            
                        </div>
                        <div>
                            <div>
                                <label>Document URL:</label><a style="padding-left:2em" target="_blank" href="#">Black Holes</a>                                
                            </div><br/>
                            
                            <label>Choose a Document:</label>
                            <form action="demo_form.asp">
                                <input type="file" name="pic" accept="pdf/*">
                                <input type="submit" value="Upload">                                
                            </form>
                        </div>
                        <p>*Note: Existing document will be overridden if a new document is chosen</p>
                    </fieldset>
                }
            </div><br />
            <div class="span3" style="padding-left:2em">
                @*<input type="submit" value="Book Now" class="btn btn-primary btn-block" />*@
                <a class="btn btn-primary btn-block" href="#" style="font-weight:bold">Submit Document</a>
            </div>
        </section>
    </div>
</div>

STS.P1.Planetarium/STS.P1.Planetarium/Views/Technical/UploadDocument.cshtml
@model STS.P1.Planetarium.Models.DocumentModel

@{
    ViewBag.Title = "UploadDocument";    
}

<h2>UploadDocument-STS Planetarium</h2>

<div class="row">
    <div class="col-md-12">
        <div class="span3" style="padding-left:0em;">
            @*<a href="@Url.Action("EditUploadedDocument", "Technical")" style="font-weight:bolder;font-size:larger">Edit Existing Documents</a>*@
        </div><br />
        <section id="reservatioPaymentForm" style="padding-left:7em">
            <div class="container">                
                @using (Html.BeginForm("UploadDocument", "Technical", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new {enctype = "multipart/form-data" ,@class = "form-horizontal", role = "form" }))
                {
                    <h2>Submit Technical Papers..</h2>
                    <hr />
                    <fieldset>
                        
                        <div>
                            <label>Paper Title*:</label>
                        </div>

                        <div>
                            <div>
                                @*<input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />*@
                                @Html.TextBoxFor(m => m.DocumentName)
                            </div>
                            <label>Author Name*:</label>
                        </div>

                        <div>
                            <div>
                                <input class='required phone' type="text" name="authorPhone" id='authorPhone' maxlength="50" value="" />
                            </div>
                            <label>Author Contact Email*:</label>
                        </div>

                        <div>
                            <div>
                                <input type="text" name="authorEmail" id='authorEmail' maxlength="64" value="" />
                            </div>
                            <label>Choose a Document:</label>
                        </div>  
                        <div>
                            <input type="file" name="technicalDocument" accept="pdf/*">
                            @*<form action="demo_form.asp">
                            <input type="submit" value="Upload"></form>*@
                        </div> <br/>                    
                    </fieldset>
                    <div class="span3" >
                        <input type="submit" value="Upload Document" class="btn btn-primary btn-block" />
                        @*<a class="btn btn-primary btn-block" style="font-weight:bold">Upload Document</a>*@                      

                    </div>
                }
            </div>
            <p style="padding-top:1em">
                @ViewBag.resultDocumentMessage
                @*<a style="padding-left:2em" target="_blank" href="@(ViewBag.resultDocumentMessage)">Document Link</a>*@
            </p>
            
        </section>
    </div>    
</div>

STS.P1.Planetarium/STS.P1.Planetarium/Views/Technical/publish.cshtml
@model STS.P1.Planetarium.Models.MovieModel

@{
    //Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>publish</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()    
        <br/><br/>
    <div id="publishForm" class="form-horizontal" >
        <h2>Publish Movie..</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MovieName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Show1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Show1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Show1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Show2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Show2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Show2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Show3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Show3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Show3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Show4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Show4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Show4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrailerURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrailerURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrailerURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MovieLength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MovieLength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MovieLength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div><br/>

        <div class="form-group" style="padding-left:4em">
            @Html.Label("Planetariums")
            <div class="col-md-10" style="padding-left:6em">
                @Html.DropDownList("planetariums", new SelectList((System.Collections.IEnumerable)ViewData["PlanetariumDropdown"], "Value", "Text"), "")
                @Html.ValidationMessageFor(model => model.PlanetariumId, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Publish Movie" class="btn btn-primary btn-block" />
            </div>
        </div>
        <h3>@Session["returnResponse"]</h3>
    </div>
    }

    <p style="padding-top:1em">
        @ViewBag.resultPublishMessage
        @*<a style="padding-left:2em" target="_blank" href="@(ViewBag.resultDocumentMessage)">Document Link</a>*@
    </p>    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

STS.P1.Planetarium/STS.P1.Planetarium/Views/Technical/publishEdit.cshtml
@{
    ViewBag.Title = "publish-STS Planetarium";    
}

<div>
    <br /><br />
    
    <div class="row" id="bookingsScreen" style="padding-left:2em">
        <div class="col-md-12">
            <section id="bookingSection" style="padding-left:2em">
                <div class="container">
                    <h2>Edit Content..</h2>
                    <br />
                    <h4>Choose Content: </h4>
                    <select name="business_state" class="dropdown" style="height:35px;width:150px">
                        <option value="">Choose Content...</option>
                        <option value='AL'>Movie</option>
                        <option value='AL'>Astronomical</option>
                        <option value='AL'>Conspiracy Theory</option>
                        <option value='AL'>Eclipse</option>
                    </select>
                </div>
            </section>

            <label>Movie Content</label>
            <section id="bookingSection" style="padding-left:2em">
                <div class="container">
                    <div id="row">
                        <div>
                            <h4>Planetarium Name: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Movie Name: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Release Date: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Timings: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Cost per Ticket: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Run Time: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <h4>Youtube Trailer URL: </h4>
                        <div style="padding-left:2em">
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <div class="row" id="AstronomyScreen" style="padding-left:2em">
        <div class="col-md-12">
            <label>Astronomical Content</label>
            <section id="bookingSection" style="padding-left:2em">
                <div class="container">
                    <div id="row">
                        <div>
                            <h4>Topic:</h4>
                            <div class="dropdown" style="padding-left:2em">
                                <select>
                                    <option value="volvo">Topic...</option>
                                    <option value="volvo">Star</option>
                                    <option value="saab">Galaxy</option>
                                    <option value="mercedes">Planet</option>
                                </select>
                            </div>
                        </div><br />
                        <div>
                            <h4>Name: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Constellation: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Brief Summary: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Youtube URL: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <div class="row" id="ConspiracyScreen" style="padding-left:2em">
        <div class="col-md-12">
            <label>Conspiracy Theory Content</label>
            <section id="bookingSection" style="padding-left:2em">
                <div class="container">
                    <div id="row">
                        <div>
                            <h4>Theory Name: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Country: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>URL: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Youtube URL: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <div class="row" id="EclipseScreen" style="padding-left:2em">
        <div class="col-md-12">
            <label>Eclipse Content</label>
            <section id="bookingSection" style="padding-left:2em">
                <div class="container">
                    <div id="row">
                        <div>
                            <h4>Eclipse Type: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Year: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Date: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Time: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <div class="row" id="SliderContent" style="padding-left:2em">
        <div class="col-md-12">
            <label>Slider Content</label>
            <section id="bookingSection" style="padding-left:2em">
                <div class="container">
                    <div id="row">
                        <div>
                            <h4>Title: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Message: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Button Title: </h4>
                            <input class='required email' type="text" name="owner_email" id='owner_email' maxlength="64" value="" />
                        </div>
                        <div>
                            <h4>Choose Image: (Must have 1500 * 450 resolution and .png extension)</h4>
                            <div>
                                <form action="demo_form.asp">
                                    <input type="file" name="pic" accept="image/*">
                                    <input type="submit" value="Upload">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <div class="span3" style="padding-left:2em">
        @*<input type="submit" value="Book Now" class="btn btn-primary btn-block" />*@
        <a class="btn btn-primary btn-block" href="#" style="font-weight:bold">Publish Content</a>
    </div>
</div>