STS.P1.Planetarium/STS.P1.Planetarium/Controllers/AstronomyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace STS.P1.Planetarium.Controllers
{
    public class AstronomyController : Controller
    {
        // GET: Astronomy
        public ActionResult information()
        {
            return View();
        }
    }
}

STS.P1.Planetarium/STS.P1.Planetarium/Views/Astronomy/information.cshtml
@{
    ViewBag.Title = "Astronomy - STS Planetarium";
}

<title>Index</title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js">
</script>
<script type="text/javascript">
    $(function () {
        $("#getInfo").click(function () {
            var banner = $("#bannerSection");
            banner.show(); 
        })
    });
</script>

<div class="row" id="bookingsScreen">
    <div class="col-md-6">
        <section id="bookingSection" style="padding-left:5em">

            <div class="container">
                <h2>Explore Stars, Galaxy, and Planets information here..</h2>
                <hr />
                @using (Html.BeginForm("information", "Astronomy", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <div id="bookingForm" style="padding-left:5em">
                        <div>
                            <h4>Topic to Explore:</h4>
                            <div class="dropdown" style="padding-left:2em">
                                <select>
                                    <option value="volvo">Select a Topic...</option>
                                    <option value="volvo">Planets</option>
                                    <option value="saab">Stars</option>
                                    <option value="mercedes">Galaxies</option>
                                    <option value="mercedes">Technical Papers</option>
                                </select>
                            </div>
                        </div><br />
                        <div>
                            <h4>Stars:</h4>
                            <div class="dropdown" style="padding-left:2em">
                                <select>
                                    <option value="volvo">Select a Star...</option>
                                    <option value="volvo">Polaris</option>
                                    <option value="saab">Sirus</option>
                                    <option value="mercedes">Betelgeuse</option>
                                </select>
                            </div>
                        </div><br />
                        <div>
                            <h4 style="display:none">Galaxies:</h4>
                            <div class="dropdown" style="padding-left:2em; display:none">
                                <select>
                                    <option value="volvo">Choose a Galaxy...</option>
                                    <option value="volvo">Sombrero</option>
                                    <option value="saab">Black Eye</option>
                                    <option value="mercedes">Grand spiral</option>
                                </select>
                            </div>
                        </div><br />
                        <div>
                            <h4 style="display:none">Planets:</h4>
                            <div class="dropdown" style="padding-left:2em ; display:none">
                                <select>
                                    <option value="">Select a Planet...</option>
                                    <option value="AGP">Jupiter</option>
                                    <option value="USP">Mars</option>
                                    <option value="NWP">Earth</option>
                                </select>
                            </div>
                        </div><br /><br/>
                        <div class="span2">
                            @*<input type="submit" value="Book Now" class="btn btn-primary btn-block" />*@
                            <a class="btn btn-primary btn-block" href="#" id="getInfo">Get Information &raquo;</a>
                        </div>
                    </div>
                }
            </div>
        </section>
    </div>
    <div class="divider" style="position: absolute; left: 50%; top: 25%; bottom: 10%; border-left: 1px solid white;"></div>
    <div class="col-md-3">
        <section id="bannerSection" style="display:none">
            <h3></h3>
            @*<div class="container">
                    <div id="row">
                        <img src="~/Content/Images/Movies/Journey-to-Space-3D-the-orange-cat.jpg" alt=""/>
                    </div>
                </div>*@
            <div class="container" style="padding-top:3em">
                <div id="row">
                    <div>
                        <h4>Star Name: </h4><label id="reservationMoiveName" style="padding-left:2em;font-weight:bold">Sirius</label>
                    </div><br />
                    <div>
                        <h4>Constellation: </h4><label id="reservationMoiveDate" style="padding-left:2em;font-weight:bold">Canis Major</label>
                    </div><br />
                    <div>
                        <h4>Brief Information: </h4>
                        <p id="reservationMoiveDate" style="padding-left:0em;display:block;margin-right:2em;font-weight:bold;text-align: justify;text-justify:inter-word">
                            Sirius (/ˈsɪriəs/) is the brightest star (in fact, a star system)
                            in the Earth's night sky. With a visual apparent magnitude of −1.46, it is almost twice
                            as bright as Canopus, the next brightest star. The name "Sirius" is derived from the Ancient
                            Greek Σείριος (Seirios), meaning "glowing" or "scorcher". The system has the Bayer designation Alpha Canis Majoris (α CMa). What the naked eye perceives as a single star is actually a binary star system, consisting of a white main-sequence star of spectral type A1V, termed Sirius A, and a faint white dwarf companion of spectral type DA2, called Sirius B. The distance separating Sirius A from its companion varies between 8.2 and 31.5 AU.[24].<br />
                        </p>
                    </div><br />
                    <h4>Video: </h4>
                    <div style="padding-left:2em">
                        <iframe width=" 500" height="338" src="http://www.youtube.com/embed/s45j2bRwHr0" frameborder="1" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div class="col-md-2">
        <div>

        </div>
    </div>

</div>